plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.smartcard.regionfix'
    compileSdk 36

    defaultConfig {
        applicationId 'dev.smartcard.regionfix'
        minSdk 26
        targetSdk 36
        versionCode 6
        versionName 'v3'
    }
}

dependencies {
    compileOnly files('libs/api-82.jar')
}
